api:
    resource: '../src/Controller/Api'
    type:     annotation
    prefix:   /api
    trailing_slash_on_root: false

app.swagger_ui:
    path: /{area}/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

main:
    resource: '../src/Controller'
    type:     annotation
    trailing_slash_on_root: false
